[package]
name = "uasat"
description = "A SAT solver based discrete mathematics and universal algebra calculator"
license = "GPLv3"
authors = ["Miklos Maroti <mmaroti@gmail.com>"]
version = "0.1.3"
edition = "2018"
repository = "https://github.com/mmaroti/uasat.rs"

[features]
default = ["minisat", "varisat", "cryptominisat", "batsat"]
wasm = ["console_error_panic_hook", "varisat"]

[dependencies]
bit-vec = "0.6"
wasm-bindgen = "0.2"
minisat = { version = "0.4", optional = true }
varisat = { version = "0.2", optional = true }
cryptominisat = { version = "5.6", optional = true }
batsat = { version = "0.4", optional = true }
splr = { git = "https://github.com/shnarazk/splr.git", branch = "master", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }

[dev-dependencies]
clippy = "*"
wasm-bindgen-cli = "0.2"

[profile.release]
lto = true
