[package]
name = "uasatrs"
description = "A SAT solver based discrete mathematics and universal algebra calculator"
license = "GPLv3"
authors = ["Miklos Maroti <mmaroti@gmail.com>"]
version = "0.1.0"
edition = "2018"
repository = "https://github.com/mmaroti/uasatrs"

[lib]
name = "uasatlib"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
clippy = "*"
wasm-bindgen-cli = "0.2"
