[package]
name = "uasat"
description = "A SAT solver based discrete mathematics and universal algebra calculator"
license = "GPLv3"
authors = ["Miklos Maroti <mmaroti@gmail.com>"]
version = "0.1.0"
edition = "2018"
repository = "https://github.com/mmaroti/uasat.rs"

[features]
default = ["minisat", "varisat"]
wasm = ["console_error_panic_hook", "varisat"]

[dependencies]
wasm-bindgen = "0.2"
bit-vec = "0.5"
minisat = { version = "0.4", optional = true }
varisat = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }

[dev-dependencies]
clippy = "*"
wasm-bindgen-cli = "0.2"

[profile.release]
lto = true
